# Generated by Django 3.0.5 on 2020-04-24 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('empcode', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=12)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employe_register.Position')),
            ],
        ),
    ]
